version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: snipster
    binary: snip
    main: ./cmd/snip
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X github.com/HrodWolfS/snipster/internal/version.Version={{.Version}}
      - -X github.com/HrodWolfS/snipster/internal/version.Commit={{.ShortCommit}}
      - -X github.com/HrodWolfS/snipster/internal/version.Date={{.Date}}

archives:
  - id: snipster-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: HrodWolfS
    name: snipster
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"

# ⚠️ COMMENTER jusqu'à création de homebrew-tap
# brews:
#   - name: snipster
#     repository:
#       owner: HrodWolfS
#       name: homebrew-tap
#     homepage: https://github.com/HrodWolfS/snipster
#     description: "Un gestionnaire de snippets local, élégant et rapide pour le terminal"
#     license: MIT
#     install: |
#       bin.install "snip"
#     test: |
#       system "#{bin}/snip", "--version"
